<?php
require '../db_connect.php';

$errors = [];
$success = null;

function handle_import($conn, $payload) {
    if (!$payload || !isset($payload['user_id']) || !isset($payload['recommendations'])) {
        return ['Invalid payload. Expecting user_id and recommendations.'];
    }

    $user_id = (int) $payload['user_id'];
    $recommendations = $payload['recommendations'];
    $rec_type = $payload['recommendation_type'] ?? 'hybrid_py';

    $del_stmt = $conn->prepare("DELETE FROM recommendations WHERE user_id = ? AND recommendation_type = ?");
    $del_stmt->bind_param('is', $user_id, $rec_type);
    $del_stmt->execute();
    $del_stmt->close();

    $ins_stmt = $conn->prepare("INSERT INTO recommendations (user_id, product_id, score, recommendation_type) VALUES (?, ?, ?, ?)");
    foreach ($recommendations as $rec) {
        $pid = (int) ($rec['product_id'] ?? 0);
        $score = (float) ($rec['score'] ?? 0);
        if ($pid <= 0) {
            continue;
        }
        $ins_stmt->bind_param('iids', $user_id, $pid, $score, $rec_type);
        $ins_stmt->execute();
    }
    $ins_stmt->close();

    return [];
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $payload = null;
    if (!empty($_FILES['json_file']['tmp_name'])) {
        $raw = file_get_contents($_FILES['json_file']['tmp_name']);
        $payload = json_decode($raw, true);
    } elseif (!empty($_POST['json_text'])) {
        $payload = json_decode($_POST['json_text'], true);
    }

    $errors = handle_import($conn, $payload);
    if (empty($errors)) {
        $success = 'Recommendations imported successfully.';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recommender Import</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 2rem; background: #f7f7f7; }
        .card { background: #fff; padding: 1.5rem; border-radius: 8px; max-width: 800px; margin: 0 auto; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        textarea { width: 100%; min-height: 220px; }
        .btn { padding: 10px 16px; border: none; background: #2563eb; color: #fff; border-radius: 6px; cursor: pointer; }
        .error { color: #b91c1c; margin-bottom: 1rem; }
        .success { color: #166534; margin-bottom: 1rem; }
        label { display: block; margin-top: 1rem; font-weight: 600; }
    </style>
</head>
<body>
    <div class="card">
        <h2>Recommender Import</h2>
        <p>Paste JSON output or upload a JSON file generated by the Python recommender.</p>

        <?php if (!empty($errors)): ?>
            <div class="error">
                <?php foreach ($errors as $err): ?>
                    <div><?php echo htmlspecialchars($err); ?></div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if ($success): ?>
            <div class="success"><?php echo htmlspecialchars($success); ?></div>
        <?php endif; ?>

        <form method="POST" enctype="multipart/form-data">
            <label for="json_text">Paste JSON</label>
            <textarea id="json_text" name="json_text" placeholder='{"user_id":1,"recommendations":[...]}'></textarea>

            <label for="json_file">Or upload JSON file</label>
            <input type="file" id="json_file" name="json_file" accept="application/json">

            <div style="margin-top: 1rem;">
                <button type="submit" class="btn">Import Recommendations</button>
            </div>
        </form>
    </div>
</body>
</html>
